### ISSUE TITLE
linux implementation compiler error

### ISSUE THREAD

**Issue by JernejL** [pBlueG/Socket#7]
in int CSocket::ssl_create(int socketid, int method)

The ifdef'd section is like this unneccesarily, both platforms need to use "const SSL_METHOD _ssl_method;", linux method uses "SSL_METHOD *_ssl_method;" which is wrong. 

So whole thing should be like this or just one line with "const SSL_METHOD *ssl_method;": 
# if (defined(WIN32) || defined(_WIN32) || defined(_WIN64))

```
    const SSL_METHOD *ssl_method;
```
# else

```
    const SSL_METHOD *ssl_method;
```
# endif

**Comment by pBlueG** [comment]
You are absolutely right, either way, it's a compiler constant so it doesn't have any effect on the code itself. I'll clean the code incase I'm updating the plugin at any point.

**Comment by JernejL** [comment]
Or put me on the socket project and i'll submit some patches myself :)

**Comment by pBlueG** [comment]
Done
